name: test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

env:
  TF_IN_AUTOMATION: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: setup terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: Cache Terraform Plugins
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: ${{ runner.temp }}/.terraform.d/plugin-cache
          key: tf-plugins-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Initialize Terraform
        run:  terraform init

      - name: Suggest Terraform Format
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-suggester@2558ba17e65a9039e73764a73009fc05fef28a46 # v1.24.3
        with:
          tool_name: terraform-fmt
          level: warning
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_level: error

      - name: Check Terraform Format
        if: github.event_name == 'push'
        run: terraform fmt -recursive -check

      - name: Validate Terraform
        uses: reviewdog/action-terraform-validate@6365bf83a0ea1fb7966229f8a59849fd82cc2de2 # v1.17.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          fail_level: error

      - name: Lint GitHub Actions
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0
        with:
          reporter: github-pr-check
          fail_level: error
          filter_mode: nofilter
